### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by brettmarshall** [taylor1791/promissory-arbiter#39]
Love your repo, would you consider including this in the bower repository?

**Comment by taylor1791** [comment]
Are you currently using `promissory-arbiter`? If so, I would love to know how you are using it. I'll have it on `bower` in the next couple of days.

**Comment by brettmarshall** [comment]
Hi, I'm using it for a weather web app I am building. Specifically, I'm controlling the initialization of functions based on when info is available; location, api response, etc. This way, if I need to add a new feature, I can publish the data to the appropriate function in the chain.

**Comment by taylor1791** [comment]
That is great! If you don't mind me asking, how did you find `promissory-arbiter`?

**Comment by taylor1791** [comment]
@brettmarshall I published the package to the bower registry. Please let me know if you have any problems and I will reopen the issue.

**Comment by brettmarshall** [comment]
Did some googling around for a pubsub solution for JavaScript. Thanks! I'll let you know if I run into any issues.
